travis:
  secure:
    BINSTAR_TOKEN: DbQnSouRpVvW50HDrMpBoW9MZatODcl9DSVxK9iRzWdh/6BRO+80WALyLuMvTArBq2CrBSwKMLwYCmhqPnc5fWePTRiMoS/7qDt0jSjZNU6LxSMqY6zgeBjosYv9fzFc61x2ZiPh0knHZNWOXTiAi6fv1NnDhqIlJQ31T6EwHCB4MENGJCdDMbkCwmraldv5MydtcqaXXL4ISZYwIYaPHio1xMP4y38h8W7KIkwDitDSWprdJfsQinVCcSDy3iPxP3ry5VI/o7tB0dy8IA2Sp2/+zk9ey12mD/gtvpUXN27E1BkKggLHkkxI7M8E28400r/OBdYJWfTbek79jHqrIqqp1dBSqRthm95pguxInbtv0YOsOJNPFomHeqmDseX5BWZeYMzOyjbxjgPbIbZXzLsAQGj83SR0SOCu6RFbz1BHGdZgG1iFccSaXdr//0PKXGqugo3/JL/a8C6l8QAzqw5t5J/2WZF9pEBSLQ7JJumfjNwbo3f/act69/5rgvl+uH9a5xlHYM98sUtldIfvBnmEMNLjdPJ1AqdNnF8IpCNI72wOa8ix4mg2iRxYuneDjID6Z3wwJOjV/IP0tUMJJLUlrN2UQZ7cc4t8VEDgrL5SpiUp8ZSBORROb3geOtcgBcMwY0uwT2pcKvrgU8WCZ0DDgpi8YGLJrGMaPX7/CSg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
